version: '3'

services:
  chatsaude:
      build:
        context: ./api
      env_file: .env
      ports:
        - '8000:80'
      volumes:
        - .:/api
      sysctls:
        - net.ipv4.tcp_keepalive_time=200
    